# "a2c" = "A2C $\\hat V(h)$"
# "asym-a2c-vhs" = "Asym-A2C $\\hat V(h, s)$"
# "asym-a2c-vhz-hh-heaven" = "Asym-A2C $\\hat V(h, z=\\text{heaven})$"
# "asym-a2c-vhz-hh-position" = "Asym-A2C $\\hat V(h, z=\\text{position})$"
# "noisy-a2c" = "Noisy A2C $\\hat V(h) + \\omega$"
# "asym-a2c-vh->vhs" = "Asym-A2C $\\hat V(h \\to (h,s))$"
# "asym-a2c-vhs->vh" = "Asym-A2C $\\hat V((h,s) \\to h)$"

"a2c" = "A2C $\\hat V(h)$"
"asym-a2c-vhs" = "A2C $\\hat V(h, s)$"
"asym-a2c-vhz-hh-heaven" = "A2C $\\hat V(h, z=\\text{heaven})$"
"asym-a2c-vhz-hh-position" = "A2C $\\hat V(h, z=\\text{position})$"
"noisy-a2c" = "A2C $\\hat V(h) + \\omega$"
"asym-a2c-vh->vhs" = "A2C $\\hat V(h \\to (h,s))$"
"asym-a2c-vhs->vh" = "A2C $\\hat V((h,s) \\to h)$"
